# Copyright 2022 Espressif Systems (Shanghai) PTE LTD
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Docker Development Image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    # Runs when chip-builds file changes
    branches: [ "main" ]

  # Can be run manually
  workflow_dispatch:

env:
  # Platforms to build the image for
  BUILD_PLATFORMS: linux/amd64,linux/arm64
  DOCKERHUB_REPO: ${{ github.repository }}

jobs:
  docker:
    # Disable the job in forks
    if: ${{ github.repository_owner == 'espressif' }}

    runs-on: ubuntu-latest
    steps:
      - name: Set variables (main branch)
        if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
        run: |
          echo "CLONE_BRANCH_OR_TAG=main" >> $GITHUB_ENV
          echo "TAG_NAME=latest" >> $GITHUB_ENV

      # Display the variables set above, just in case.
      - name: Check variables
        run: |
          echo "CLONE_BRANCH_OR_TAG: $CLONE_BRANCH_OR_TAG"
          echo "CHECKOUT_REF: $CHECKOUT_REF"
          echo "TAG_NAME: $TAG_NAME"

      # The following steps are the standard boilerplate from
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU for multiarch builds
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: tools/docker
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.TAG_NAME }}
          platforms: ${{ env.BUILD_PLATFORMS }}
          build-args: |
            ESP_MATTER_CLONE_URL=${{ github.server_url }}/${{ github.repository }}.git
            ESP_MATTER_CLONE_BRANCH_OR_TAG=${{ env.CLONE_BRANCH_OR_TAG }}
            ESP_MATTER_CLONE_SHALLOW=1
